### ISSUE TITLE
Mod compat problem with Yanny' Stone Age

### ISSUE THREAD

**Issue by LokyLive** [oitsjustjose/Natural-Progression#29]
Minecraft Version: 1.16.4
Forge version:   35.1.32

Mod : 
- NaturalProgression-1.16.4-1.3.0 
- Yanny's Stone Age 1.16.4-1.2.5
   (https://www.curseforge.com/minecraft/mc-mods/stone-age-by-yanny)      

Problem:

When i try to broke tree using Stone or Bone axe from Yanny's stone age mod it display the "wrong tool message" and i can't break trees

**Comment by oitsjustjose** [comment]
This would be an issue with Yanny's stone age mod. For their axes, they should add `.addToolType(ToolType.AXE, 0)`  to their item initializers. I would [make an issue](https://github.com/yanny7/StoneAge/issues/new?assignees=&labels=bug&template=bug_report.md&title=) and refer to this issue so that the author can easily find the solution :)
