### ISSUE TITLE
Collection of ideas

### ISSUE THREAD

**Issue by Terpo** [oitsjustjose/Natural-Progression#7]
You may want to extract that ideas in new issues if you like them. ;)

Dimension blacklist:
-add a boolean to switch between whitelist and blacklist mode
Reason: if another mod adds new dimensions, that are created ingame by the player, you need to adjust the blacklist over and over again
- maybe the default should be whitelist and overworld ?

Flint recipe:
Sometimes it can be really frustrating in the early game to find flint as the drop chance is quite random. The easiest solution would be the common "3 Gravel -> 1 Flint" recipe but to be fair... thats boring. Maybe you can come up with a interesting ingame way to crush flint? I think a cool way would be using the fall height of the player. Landing on gravel from a height higher than 2-3 block will crush it into a flint?
Another idea would be the usage of pebbles on gravel that increase the drop chance of flint.

Block break mechanic:
As interesting the wood break mechanic is, it is quite confusing for new players. Even if you look up axe in JEI, you will not find your hatched and so you have no idea on how to progress.
Also, if other players are joking around they could trap a new player with would logs or stone. Maybe dropping nothing instead of preventing the block harvest would be better?
Or even better.... knocking wood with your hands / pebbles will sometimes drop sticks?

Stripped wood recipes:
The next thing is on how to progress with your first log. Having a "Wood + Axe -> Stripped Wood" recipe would be really nice. Otherwise you end up chopping down a tree, placing the log again, just to strip it. 

JEI integration / tooltips:
Without any knowledge it is really hard to find out how to progress. Maybe adding a JEI description for wood or stripped would could be helpful. Event cooler would be a JEI category, which uses your saw or axe as an icon and simply shows the way to get planks. 

Disable enchantibility for pebbles:
**Edit: It seems every item or blocks shows up as enchantable, so this might be a problem with Just Enough Resources**
![grafik](https://user-images.githubusercontent.com/4256058/68527690-10761b80-02ea-11ea-80b7-93c42b2eace5.png)
hint: https://github.com/Terpo/Waterworks/blob/1.14/src/main/java/org/terpo/waterworks/item/ItemPipeWrench.java

Early game repairing:
Maybe adding a flint to your hatched / saw in the crafting table could restore 1/3 or 1/2 of the durability?

Reduce wood tool durability:
It would be helpful to have a config option to reduce the durability of wood tools. Some other mods may use the wood tools in their recipes, so it would be helpful to have the item without the possibility to use them.

**Comment by oitsjustjose** [comment]
Wow! These are a lot of great ideas! I'll probably take you up on some and leave others (I mean no offense in doing so, just maybe not the vibe of the gameplay I'm aiming for

> Dimension Blacklist to Whitelist

This makes sense, so I'll probably invert that config option as you mentioned

> Flint Recipe

Yeah... a bit too boring. After all, I assume you've seen that you can knap pebbles into flint by holding a pebble in the mainhand and offhand and hold right-click (while not facing a block). 

> Block Break Mechanic

True, but if I add knapping JEI integration, then you'd see you get flint, prompting you to look at uses for flint, allowing you to see the uses of flint and therefore the hatchet. I can always rename it Flint Axe too. That's fine with me.

> Stripped Wood Recipes

Yes. I've been playing with it and this has been a HUGE hassle and I agree that something needs to be done. This may be an ax-exclusive recipe since it's impossibly difficult IRL to de-bark with a saw.

> JEI integration

Yes, see above but yeah, this is a super important thing that I've been slacking on. For both knapping pebbles into flint, and for the sawing / axing recipes (and potential de-barking recipes)

> Pebble enchanting [????]

Uh what?? Yeah absolutely shouldn't be happening so I'll check if it actually works regardless of what JER says.

> Repairing

Hmm, I'd argue that this is *too* easy, though I see where you're coming from. 

> Reduced wood durability

I'd probably just make them useless rather than low-durability (e.g. they break nothing)

_____

I'm taking notes of these ideas though! I like them a lot!

**Comment by oitsjustjose** [comment]
> Pebble enchanting [????]

Ok thank god, that's just a JER bug

<center>
<img width="448" alt="Screen Shot 2019-11-09 at 8 05 30 PM" src="https://user-images.githubusercontent.com/3887324/68537599-4fc55c00-032c-11ea-8b39-eb158ae3da02.png">
</center>

**Comment by oitsjustjose** [comment]
Ok, JEI compat is integrated!

**Comment by oitsjustjose** [comment]
Ok, so log stripping with a saw has been implemented and documented using JEI, and the config blacklist has been turned to a whitelist :smile:

**Comment by oitsjustjose** [comment]
Alright, I think everything's implemented!!
