### ISSUE TITLE
Pebbles and Twigs Only Spawn Underwater Now

### ISSUE THREAD

**Issue by CraftyZombie** [oitsjustjose/Natural-Progression#92]
![2024-07-05_09 13 13](https://github.com/oitsjustjose/Natural-Progression/assets/70306455/d02efd97-c7bb-46cd-ab5c-57f721cf89a2)

Versions:
Minecraft: 1.20.1
Forge: 47.3.4
NatProg: 2.3.8

Logs:
https://gist.github.com/CraftyZombie/9421a63acb2cf36d08ef30413d7bb286

Config:
Unaltered.

Description:
I've noticed that in 2.3.8 (I don't remember about 2.3.7), pebbles and twigs will only spawn underwater. I've checked everywhere for them. The rest of the world is completely barren. Downgrading to 2.3.6 makes pebbles spawn elsewhere again. There's no way it's a coincidence, but I don't know the cause of it either.

**Comment by xSyphel** [comment]
The exact same issue here as well. Reverting to 2.3.7 fixes the no pebble world generation issue.

**Comment by IDragen** [comment]
The same error happens to me, Pebbles and twigs are not generated on the surface and only under water.

**Comment by sharkweekthings** [comment]
also experiencing the same issue. All pebbles / twigs only exist under water. 

Forge / 1.20.1-47.3.7

If I downgrade to 2.3.7 there is a conflict with Silent Gear where even when the Tool Neutering is set to "False" it neuters the Silent Tools.

**Comment by kaiserczar** [comment]
Chiming in since I just came across this issue as well. I expect the issue stems from this commit that was part of 2.3.8: https://github.com/oitsjustjose/Natural-Progression/commit/5eb0c26e4c40a328db546e910b21523d6f36a278

The `Utils.inNonWaterFluid` method is used in the worldgen for pebbles and twigs, and the logic got reversed when going from `.liquid()` to `.getFluidState().isEmpty()`.

**Comment by oitsjustjose** [comment]
Thanks a ton @kaiserczar :heart: merged, closing this ticket -- new release later today with this fix.
